name: smb
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - aom=3.9.1=h7bae524_0
  - arrow-cpp=21.0.0=h9e9184e_1
  - aws-c-auth=0.9.0=h79febb2_2
  - aws-c-cal=0.9.2=hd08b81e_1
  - aws-c-common=0.12.4=h6caf38d_0
  - aws-c-compression=0.3.1=habbe1e8_6
  - aws-c-event-stream=0.5.6=hd40f934_1
  - aws-c-http=0.10.4=he148155_1
  - aws-c-io=0.21.4=h89d1e94_1
  - aws-c-mqtt=0.13.3=h8d8bef9_4
  - aws-c-s3=0.8.7=h79febb2_0
  - aws-c-sdkutils=0.2.4=habbe1e8_1
  - aws-checksums=0.2.7=habbe1e8_2
  - aws-crt-cpp=0.34.0=hee39554_0
  - aws-sdk-cpp=1.11.638=h35fa3df_0
  - blas=2.302=openblas
  - blas-devel=3.11.0=2_h11c0a38_openblas
  - blosc=1.21.6=h5499902_0
  - bokeh=3.8.1=pyhd8ed1ab_0
  - bottleneck=1.4.2=py311h03d0aa3_1
  - brotli-python=1.2.0=py311h5b255a4_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cftime=1.6.5=py311h0f6c237_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - contourpy=1.3.3=py311h20e30b6_0
  - cytoolz=1.1.0=py311haa24f5a_0
  - dask=2025.11.0=pyhcf101f3_0
  - dask-core=2025.11.0=pyhcf101f3_0
  - dav1d=1.2.1=hb547adb_0
  - distributed=2025.11.0=pyhcf101f3_0
  - esmf=8.9.0=nompi_h0ef9198_3
  - expat=2.7.3=h982b769_0
  - fontconfig=2.15.0=h1383a14_1
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - gflags=2.2.2=hf9b8971_1005
  - glog=0.5.0=h5c6a83d_0
  - graphite2=1.3.14=hec049ff_2
  - gsl=2.7=h6e638da_0
  - harfbuzz=10.2.0=he637ebf_1
  - hdf4=4.2.15=h1a38d6a_5
  - hdf5=1.14.6=nompi_he65715a_103
  - icu=73.2=hc8870d7_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jpeg=9e=h1a8c8d9_3
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libaec=1.1.4=h51d1e36_0
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libavif=1.3.0=hb06b76e_2
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.11.0=2_h51639a9_openblas
  - libbrotlicommon=1.0.9=h80987f9_9
  - libbrotlidec=1.0.9=h80987f9_9
  - libbrotlienc=1.0.9=h80987f9_9
  - libcblas=3.11.0=2_hb0561ab_openblas
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.3=haf25636_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_14
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libgfortran=15.2.0=h07b0088_14
  - libgfortran5=15.2.0=hdae7583_14
  - libglib=2.84.4=h7a3292d_0
  - libgrpc=1.71.0=hf667ad3_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - liblapack=3.11.0=2_hd9741b5_openblas
  - liblapacke=3.11.0=2_h1b118fd_openblas
  - libnetcdf=4.9.3=nompi_h6808abe_102
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.51=hfab5511_0
  - libprotobuf=5.29.3=hccd9074_0
  - libre2-11=2024.07.02=h313beb8_0
  - libsqlite=3.51.1=h9a5124b_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h367c460_0
  - libudunits2=2.2.28=h5f3f34b_3
  - libwebp-base=1.6.0=h07db88b_0
  - libxml2=2.13.9=h528a072_0
  - libzip=1.11.2=h1336266_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.6=h4a912ad_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py311hbc89d72_0
  - lz4-c=1.9.4=hb7217d7_0
  - markupsafe=3.0.2=py311h80987f9_0
  - msgpack-python=1.1.1=py311h313beb8_0
  - narwhals=2.13.0=pyhcf101f3_0
  - nco=5.3.6=hd1afe45_0
  - ncurses=6.5=hee39554_0
  - netcdf-fortran=4.6.2=nompi_h799d18b_102
  - netcdf4=1.7.2=py311hf82d5f1_2
  - numexpr=2.14.1=py311h5fbe615_0
  - numpy=2.3.5=py311h4bb6f22_0
  - numpy-base=2.3.5=py311h23175f9_0
  - openblas=0.3.30=openmp_hea878ba_3
  - openssl=3.6.0=h5503f6c_0
  - orc=2.2.0=hec253e6_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h3f644e9_1
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.46=h7125dd6_0
  - pillow=12.0.0=py311he2d6fe4_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h81086ad_1
  - proj=9.3.1=h93d94ba_0
  - psutil=7.0.0=py311haa24f5a_1
  - pyarrow=21.0.0=py311hc6ded6b_0
  - pyproj=3.6.1=py311h041c639_1
  - pyremap=2.1.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311h091b9d3_0
  - rav1e=0.7.1=h0716509_3
  - re2=2024.07.02=h48ca7d4_0
  - readline=8.3=h0b18652_0
  - scipy=1.16.3=py311h08a1045_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sqlite=3.51.0=hab6afd1_0
  - svt-av1=3.1.2=h12ba402_0
  - tblib=3.2.2=pyhcf101f3_0
  - tempest-remap=2.2.0=haf6a4b4_8
  - tk=8.6.15=hcd8a7d5_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.1=py311h80987f9_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - utf8proc=2.6.1=h80987f9_1
  - wheel=0.45.1=py311hca03da5_0
  - xarray=2025.11.0=pyhcf101f3_0
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h925e9cb_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=hd0aec43_5
prefix: /Users/jonniebarnsley/opt/anaconda3/envs/smb
